"""Optional Demucs vocal-stem candidate for lyrics-aligner."""
from __future__ import annotations

import re
import tempfile
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator


_LRC_LINE_RE = re.compile(r"\[(\d+):(\d+(?:\.\d+)?)\]\s*(.*)")
_WORD_RE = re.compile(r"[a-z0-9]+")


@dataclass(frozen=True)
class AlignmentCandidate:
    """A lyrics-aligner result and its no-ground-truth selection metadata."""

    lrc: str
    source: str
    quality: float

    def __iter__(self) -> Iterator[str]:
        """Keep unpacking compatibility for callers from before the dataclass."""
        yield self.lrc
        yield self.source


def is_available() -> bool:
    """Return whether the optional Demucs runtime can be imported."""
    try:
        import demucs  # noqa: F401
        import soundfile  # noqa: F401
        import torch  # noqa: F401
    except ImportError:
        return False
    return True


def _parse_lrc(raw_lrc: str) -> list[tuple[float, str]]:
    parsed: list[tuple[float, str]] = []
    for line in raw_lrc.splitlines():
        match = _LRC_LINE_RE.match(line.strip())
        if not match or not match.group(3).strip():
            continue
        parsed.append(
            (
                int(match.group(1)) * 60 + float(match.group(2)),
                match.group(3).strip(),
            )
        )
    return parsed


def _normalize_text(text: str) -> str:
    return " ".join(_WORD_RE.findall(text.lower()))


def _repeated_block_consistency(
    lines: list[tuple[float, str]],
    plain_lines: list[str],
    *,
    block_size: int = 4,
) -> float:
    """Score repeated lyric blocks whose internal timing should stay stable."""
    normalized = [_normalize_text(text) for text in plain_lines if text.strip()]
    if len(lines) != len(normalized):
        return 0.0

    block_scores: list[float] = []
    for start in range(len(normalized) - block_size + 1):
        block = tuple(normalized[start : start + block_size])
        occurrences = [
            index
            for index in range(len(normalized) - block_size + 1)
            if tuple(normalized[index : index + block_size]) == block
        ]
        if len(occurrences) < 2 or start != occurrences[0]:
            continue
        reference = [
            lines[occurrences[0] + offset][0] - lines[occurrences[0]][0]
            for offset in range(1, block_size)
        ]
        for occurrence in occurrences[1:]:
            actual = [
                lines[occurrence + offset][0] - lines[occurrence][0]
                for offset in range(1, block_size)
            ]
            deviation = sum(abs(left - right) for left, right in zip(reference, actual))
            block_scores.append(max(0.0, 1.0 - deviation / 15.0))
    return sum(block_scores) / len(block_scores) if block_scores else 0.5


def candidate_quality(raw_lrc: str, plain_lyrics: str) -> float:
    """Return a no-ground-truth quality score for a lyrics-aligner candidate."""
    expected = [line for line in plain_lyrics.splitlines() if line.strip()]
    lines = _parse_lrc(raw_lrc)
    if not expected or not lines:
        return 0.0

    coverage = min(len(lines), len(expected)) / len(expected)
    monotonic = sum(
        current[0] > previous[0]
        for previous, current in zip(lines, lines[1:])
    ) / max(1, len(lines) - 1)
    repeated = _repeated_block_consistency(lines, expected)
    return coverage * 10.0 + monotonic * 2.0 + repeated * 5.0


@contextmanager
def separated_vocal_audio(audio_path: str, *, device: str) -> Iterator[str]:
    """Yield a temporary 44.1 kHz vocal stem generated by optional Demucs."""
    import numpy as np
    import soundfile as sf
    import torch
    import torchaudio.functional as functional
    from demucs.apply import apply_model
    from demucs.pretrained import get_model

    data, sample_rate = sf.read(audio_path, dtype="float32", always_2d=True)
    waveform = torch.from_numpy(np.asarray(data.T, dtype=np.float32).copy())
    if waveform.shape[0] == 1:
        waveform = waveform.repeat(2, 1)
    if sample_rate != 44100:
        waveform = functional.resample(waveform, sample_rate, 44100)

    demucs_device = "cuda" if device == "cuda" and torch.cuda.is_available() else "cpu"
    model = get_model("htdemucs").to(demucs_device).eval()
    with torch.no_grad():
        separated = apply_model(
            model,
            waveform.unsqueeze(0).to(demucs_device),
            device=demucs_device,
        )
    vocals = separated[0, 3].mean(dim=0).detach().cpu().numpy()

    with tempfile.TemporaryDirectory(prefix="pylrcget-demucs-") as temporary:
        output = Path(temporary) / f"{Path(audio_path).stem}-vocals.wav"
        sf.write(output, vocals, 44100)
        yield str(output)


__all__ = [
    "AlignmentCandidate",
    "candidate_quality",
    "is_available",
    "separated_vocal_audio",
]
